name: language_corrector
description: Language corrector app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_bloc: 8.0.1

  # di
  get_it: 7.2.0

  # navigation
  auto_route: 4.0.1

  # networking
  dio: 4.0.6

  # database
  shared_preferences: 2.0.15
  path_provider: 2.0.10

  # utils
  equatable: 2.0.3
  google_fonts: 3.0.1
  dartz: 0.10.1
  copy_with_extension: 4.0.2

  # tools
  flutter_quill: ^5.0.3
  cupertino_icons: 1.0.4

  # ui
  step_progress_indicator: ^1.0.2
  top_snackbar_flutter: 1.1.1
#  font_awesome_flutter: ^10.1.0
  auto_size_text: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: 4.0.0
  build_runner: 2.1.11
  flutter_lints: 2.0.1
  copy_with_extension_gen: 4.0.2

flutter:
  assets:
    - assets/images/
  uses-material-design: true
